### ISSUE TITLE
Adding users to groups not atomic

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/cf-uaac#25]
# Issue

UAA fails to modify user groups while executing multiple user modify requests in parallel.
# Context

see https://github.com/cloudfoundry/uaa/issues/372 for full description. It turned out that it is actually uaac issue and there is a suggestion of how the issue can be worked around. Perhaps `uaac` should implement this.

**Comment by sreetummidi** [comment]
See comments in linked issue

**Comment by dcarley** [comment]
@sreetummidi this issue was created to supersede the linked issue. Could you give more context about why it was closed?

The intention is that `uaac member add` should use `POST /Groups/group-uuid/members` instead of `PUT /Groups/group-uuid`, so that it's more resilient and user friendly when other concurrent UAA operations are happening. Do you foresee any problems with that?

**Comment by cbguder** [comment]
@mtekel @dcarley We have stopped active development on cf-uaac, and are planning to build a replacement for it. I will close this issue now.
