### ISSUE TITLE
Invalid client ID opsman

### ISSUE THREAD

**Issue by prasadpete** [cloudfoundry/cf-uaac#39]
Something went wrong, I get below.
```
$http_proxy= https_proxy= uaac me
error response:
{
  "error": "unauthorized_client",
  "error_description": "Invalid client ID opsman"
}
```
I'm not even able to login to PCF Ops Manager. What's wrong here please ?

**Comment by plfx** [comment]
Hello @prasadpete 

This error message combined with your inability to login to opsman means that somehow the opsman client on the opsman UAA instance has been removed or renamed. Since opsman is a proprietary offering, you are able to take advantage of [Pivotal GSS](https://support.pivotal.io/) to work through the issue.

I am closing this issue. If you determine after solving your Opsman problem that a problem does exist in uaac, please re-open.
