### ISSUE TITLE
install cf-uaac error

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cf-uaac#48]
In Ubuntu 16.04:

root@qiyedal10:~# gem install cf-uaac
Building native extensions.  This could take a while...
ERROR:  Error installing cf-uaac:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/eventmachine-1.2.5/ext
/usr/bin/ruby2.3 -r ./siteconf20180102-3734-y3a9sq.rb extconf.rb
checking for main() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-ssl-dir
	--without-ssl-dir
	--with-ssl-include
	--without-ssl-include=${ssl-dir}/include
	--with-ssl-lib
	--without-ssl-lib=${ssl-dir}/lib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
	--with-cryptolib
	--without-cryptolib
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /usr/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:8:in `block in check_libs'
	from extconf.rb:8:in `each'
	from extconf.rb:8:in `all?'
	from extconf.rb:8:in `check_libs'
	from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/eventmachine-1.2.5 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.5/gem_make.out

**Comment by camelpunch** [comment]
This is a failure to install the C extensions for https://github.com/eventmachine/eventmachine

NB: `You have to install development tools first` and `please check the mkmf.log which can be found here`.

You're probably missing `build-essential` and/or a `-dev` deb package for a dependency.

**Comment by biskandar** [comment]
Same here ...

$ sudo snap install ruby --classic
ruby 2.7.1 from Ruby core team (rubylang✓) installed

$ gem install cf-uaac
Fetching httpclient-2.8.3.gem
Fetching multi_json-1.12.2.gem
Fetching highline-1.7.10.gem
Fetching public_suffix-4.0.5.gem
Fetching launchy-2.5.0.gem
Fetching eventmachine-1.2.7.gem
Fetching addressable-2.7.0.gem
Fetching cf-uaa-lib-3.14.3.gem
Fetching cf-uaac-4.2.0.gem
Fetching cookiejar-0.3.3.gem
Fetching em-socksify-0.3.2.gem
Fetching http_parser.rb-0.6.0.gem
Fetching em-http-request-1.1.6.gem
Fetching json_pure-1.8.6.gem
Fetching rack-1.6.13.gem
Successfully installed httpclient-2.8.3
Successfully installed multi_json-1.12.2
Successfully installed cf-uaa-lib-3.14.3
Successfully installed highline-1.7.10
Building native extensions. This could take a while...
ERROR:  Error installing cf-uaac:
	ERROR: Failed to build gem native extension.

    current directory: /home/xxx/.gem/gems/eventmachine-1.2.7/ext
/snap/bin/ruby -I /snap/ruby/181/lib/ruby/2.7.0 -r ./siteconf20200827-18404-vp711t.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/snap/ruby/181/bin/$(RUBY_BASE_NAME)
	--with-ssl-dir
	--without-ssl-dir
	--with-ssl-include
	--without-ssl-include=${ssl-dir}/include
	--with-ssl-lib
	--without-ssl-lib=${ssl-dir}/lib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
	--with-crypto-dir
	--without-crypto-dir
	--with-crypto-include
	--without-crypto-include=${crypto-dir}/include
	--with-crypto-lib
	--without-crypto-lib=${crypto-dir}/lib
	--with-cryptolib
	--without-cryptolib
/snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:582:in `try_link'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:801:in `try_func'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:1029:in `block in have_library'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
	from /snap/ruby/181/lib/ruby/2.7.0/mkmf.rb:1024:in `have_library'
	from extconf.rb:8:in `block in check_libs'
	from extconf.rb:8:in `all?'
	from extconf.rb:8:in `check_libs'
	from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/xxx/.gem/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/xxx/.gem/gems/eventmachine-1.2.7 for inspection.
Results logged to /home/xxx/.gem/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/gem_make.out
